import type { Application, AnswerEntry, Reminder, HealthScore } from '@/types'

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: '1',
    formTitle: 'Google STEP Internship 2026',
    organization: 'Google',
    sourceUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSf6g7A_st...',
    submittedAt: '2026-05-27T10:30:00Z',
    status: 'Rejected',
    fieldCount: 11,
    wordCount: 843,
    tags: ['internship', 'engineering'],
    fields: [
      { id: 'q1', question: 'Why do you want to join the Google STEP program?', answer: 'The opportunity to work alongside senior engineers on planetary-scale infrastructure is exactly where I want to grow. I\'ve spent the last year working on distributed caching systems and I want to learn from engineers solving these problems at Google\'s scale.' },
      { id: 'q2', question: 'Describe a complex technical problem you solved.', answer: 'I engineered an automated caching layer for a scheduler app that was bottlenecked during concurrent sign-up events. By implementing a write-through cache with Redis and optimizing the DB query plan, I reduced average response time from 4.2s to 340ms.' },
      { id: 'q3', question: 'What is your expected graduation date?', answer: 'May 2027' },
    ],
  },
  {
    id: '2',
    formTitle: 'Y Combinator W26 Batch Application',
    organization: 'Y Combinator',
    sourceUrl: 'https://docs.google.com/forms/d/e/YC_W26_application...',
    submittedAt: '2026-05-22T14:15:00Z',
    status: 'Heard back',
    fieldCount: 8,
    wordCount: 612,
    tags: ['startup', 'fellowship'],
    fields: [
      { id: 'q1', question: 'Describe your company in 50 words or less.', answer: 'Applid is a Chrome extension that silently captures every Google Form submission applicants make — jobs, fellowships, grants — and builds a permanent, searchable answer database with zero manual input.' },
      { id: 'q2', question: 'What is your monthly growth rate?', answer: 'We are pre-launch but have 340 people on our waitlist after 2 weeks of organic sharing.' },
    ],
  },
  {
    id: '3',
    formTitle: 'Stripe Summer Engineering 2026',
    organization: 'Stripe',
    sourceUrl: 'https://docs.google.com/forms/d/e/Stripe_Summer_Eng...',
    submittedAt: '2026-05-18T09:00:00Z',
    status: 'Submitted',
    fieldCount: 6,
    wordCount: 490,
    tags: ['internship', 'engineering'],
    fields: [
      { id: 'q1', question: 'Why Stripe?', answer: 'Stripe\'s obsession with developer experience and its position as the infrastructure layer for the internet economy is where I want to build. I\'ve built on the Stripe API and the quality of the documentation and SDK design changed how I think about product.' },
      { id: 'q2', question: 'Describe your most impactful project.', answer: 'Built a real-time collaborative code editor using CRDTs and WebSockets, supporting 50 concurrent users with sub-100ms sync latency. Used by 200 students at my university.' },
    ],
  },
  {
    id: '4',
    formTitle: 'Notion Growth Lead 2026',
    organization: 'Notion',
    sourceUrl: 'https://docs.google.com/forms/d/e/Notion_Growth_Lead...',
    submittedAt: '2026-05-15T16:45:00Z',
    status: 'Waiting',
    fieldCount: 9,
    wordCount: 720,
    tags: ['full-time', 'growth'],
    fields: [
      { id: 'q1', question: 'Describe your experience with PLG growth strategies.', answer: 'Scaled a SaaS product from 0 to 50k MAU using bottom-up product-led motion, content flywheels, and community-driven activation loops over 18 months.' },
    ],
  },
  {
    id: '5',
    formTitle: 'Figma Product Designer Role',
    organization: 'Figma',
    sourceUrl: 'https://docs.google.com/forms/d/e/Figma_Designer...',
    submittedAt: '2026-05-10T11:20:00Z',
    status: 'Accepted',
    fieldCount: 7,
    wordCount: 580,
    tags: ['full-time', 'design'],
    fields: [
      { id: 'q1', question: 'What design tools are you most proficient in?', answer: 'Figma (obviously), Tailwind styling systems, Framer Motion, and Adobe Creative Suite. I\'ve been a Figma power user for 3 years and have contributed to two open-source component libraries.' },
    ],
  },
  {
    id: '6',
    formTitle: 'OpenAI Research Fellowship 2026',
    organization: 'OpenAI',
    sourceUrl: 'https://docs.google.com/forms/d/e/OpenAI_Fellowship...',
    submittedAt: '2026-05-05T08:30:00Z',
    status: 'Waiting',
    fieldCount: 12,
    wordCount: 1100,
    tags: ['fellowship', 'research'],
    fields: [
      { id: 'q1', question: 'Describe your research background.', answer: 'Two years working on mechanistic interpretability, focusing on circuit-level analysis of transformer models using activation patching and sparse autoencoders.' },
    ],
  },
]

export const MOCK_ANSWERS: AnswerEntry[] = [
  {
    id: 'a1',
    question: 'Why are you excited to join this team?',
    answer: 'The opportunity to work alongside senior engineers on planetary-scale infrastructure is peerless. I want to learn distributed systems design under real constraints, not toy problems.',
    applicationId: '1',
    organization: 'Google',
    formTitle: 'Google STEP Internship 2026',
    submittedAt: '2026-05-27T10:30:00Z',
    usageCount: 7,
    tags: ['WHY US', 'motivation'],
  },
  {
    id: 'a2',
    question: 'Describe a complex technical problem you solved.',
    answer: 'I engineered an automated caching layer for a scheduler app that was bottlenecked during concurrent sign-up events. Reduced response time from 4.2s to 340ms using Redis write-through cache.',
    applicationId: '1',
    organization: 'Google',
    formTitle: 'Google STEP Internship 2026',
    submittedAt: '2026-05-27T10:30:00Z',
    usageCount: 12,
    tags: ['TECHNICAL', 'engineering'],
  },
  {
    id: 'a3',
    question: 'Why do you want this role specifically?',
    answer: 'Stripe\'s obsession with developer experience and its position as the infrastructure layer for the internet economy is where I want to build. The quality of the API design changed how I think about product.',
    applicationId: '3',
    organization: 'Stripe',
    formTitle: 'Stripe Summer Engineering 2026',
    submittedAt: '2026-05-18T09:00:00Z',
    usageCount: 4,
    tags: ['WHY US', 'motivation'],
  },
  {
    id: 'a4',
    question: 'Describe your most impactful project.',
    answer: 'Built a real-time collaborative code editor using CRDTs and WebSockets, supporting 50 concurrent users with sub-100ms sync latency. Used by 200 students at my university.',
    applicationId: '3',
    organization: 'Stripe',
    formTitle: 'Stripe Summer Engineering 2026',
    submittedAt: '2026-05-18T09:00:00Z',
    usageCount: 8,
    tags: ['PROJECT', 'technical'],
  },
  {
    id: 'a5',
    question: 'What is your biggest weakness?',
    answer: 'I tend to over-engineer solutions before validating the problem. I\'ve been working on this by setting explicit timebox constraints and shipping MVPs before reaching for elegant abstractions.',
    applicationId: '4',
    organization: 'Notion',
    formTitle: 'Notion Growth Lead 2026',
    submittedAt: '2026-05-15T16:45:00Z',
    usageCount: 3,
    tags: ['BEHAVIORAL', 'self-awareness'],
  },
]

export const MOCK_REMINDERS: Reminder[] = [
  {
    id: 'r1',
    applicationId: '4',
    organization: 'Notion',
    formTitle: 'Notion Growth Lead 2026',
    submittedAt: '2026-05-15T16:45:00Z',
    daysSince: 16,
    type: 'follow-up',
    message: 'You submitted 16 days ago and haven\'t heard back. Typical response window for this type of role is 10–14 days. Consider sending a polite follow-up.',
    dismissed: false,
  },
  {
    id: 'r2',
    applicationId: '6',
    organization: 'OpenAI',
    formTitle: 'OpenAI Research Fellowship 2026',
    submittedAt: '2026-05-05T08:30:00Z',
    daysSince: 26,
    type: 'follow-up',
    message: 'No reply in 26 days. Fellowship programs typically respond within 3–4 weeks. This one may be worth a follow-up or a status check on their website.',
    dismissed: false,
  },
  {
    id: 'r3',
    applicationId: '3',
    organization: 'Stripe',
    formTitle: 'Stripe Summer Engineering 2026',
    submittedAt: '2026-05-18T09:00:00Z',
    daysSince: 13,
    type: 'check-status',
    message: 'Submitted 13 days ago. Engineering internship timelines vary — if you haven\'t confirmed receipt, this is a good time to check.',
    dismissed: false,
  },
]

export const MOCK_HEALTH: HealthScore = {
  overall: 72,
  submitted: 6,
  responseRate: 67,
  avgWaitDays: 11,
  acceptanceRate: 17,
  trend: 'up',
  byCategory: [
    { label: 'Engineering Internships', count: 3, responses: 2 },
    { label: 'Full-time Roles', count: 2, responses: 1 },
    { label: 'Fellowships & Research', count: 2, responses: 1 },
  ],
}
